### ISSUE TITLE
GDPR cookie compliance

### ISSUE THREAD

**Issue by hemebond** [hemebond/quaddicted#26]
- [ ] If no consent cookie then no other cookies should be set
- [ ] If consent cookie is missing or declined, then no forms, which require a CSRF cookie, should be presented to the user
- [ ] If no consent cookie then all pages with forms (and hence CSRF tokens) should include a modal asking for consent, and reload the page on selection

**Comment by hemebond** [comment]
No cookies should be set until the user has granted or declined consent to set cookies.  Re-opened with new tasks.

**Comment by SpiritQuaddicted** [comment]
Brrrr, so complicated and overkill for sites like this. Maybe there is some Django add-on that does it?

**Comment by hemebond** [comment]
I'm going to remove it completely. The site does not use any non-essential or third-party cookies so a banner or warning is not required.

**Comment by SpiritQuaddicted** [comment]
Are you 100% sure about that? To my knowledge being restricted to first-party cookies does not remove the need for consent (or information at least).

**Comment by hemebond** [comment]
Yip. Quaddicted only uses functional cookies (sessions). [Github just removed their cookie banner](https://github.blog/2020-12-17-no-cookie-for-you/) for the same reason.
