### ISSUE TITLE
Map detail page features

### ISSUE THREAD

**Issue by hemebond** [hemebond/quaddicted#3]
# PAK download link
A link to the latest version of the files packaged properly into a PAK file and compressed into a zip. Useful for third-party tools wanting easy installation and management. 

~~# ZIP download link per version
Each time a file is uploaded for a map it will be listed, ordered according to the newest time stamp of the files inside.~~

# Tags
Clicking on a tag takes the user to the map package list page filtered to only show maps with that tag.

# Suggest new tags
Allow users to suggest new tags for a map entry. All suggestions need to be approved by staff. 

# Flag map problem 
Allow users to “flag” maps and provide a comment about the problem. 

# Reviews
Allow users to write a review on each map entry. Replaces the current “comments” system. Rating contributed to the total average rating for the map.

**Comment by SpiritQuaddicted** [comment]
> # PAK download link
> 
> A link to the latest version of the files packaged properly into a PAK file and compressed into a zip. Useful for third-party tools wanting easy installation and management.

I *really* suggest not even thinking about that for now. You end up with dependencies, opinions and worse. Let this be an issue for the third-party tools to handle. Quaddicted must *not* generate new files.

> # Tags
> 
> Clicking on a tag takes the user to the map package list page filtered to only show maps with that tag.

Yeee!

> # Suggest new tags
> 
> Allow users to suggest new tags for a map entry. All suggestions need to be approved by staff.

Yeah!

> # Flag map problem
> 
> Allow users to “flag” maps and provide a comment about the problem.

Woot! Publically shown would be best.

> # Reviews
> 
> Allow users to write a review on each map entry. Replaces the current “comments” system. Rating contributed to the total average rating for the map.

Comments without ratings must be possible too. Ratings must be changeable forever, with a cooldown period between changes. Comments/reviews must not be editable after a short window. If there must be a differentiation between comments and ratings I would recommend adding a flag people can tick for their comments. Then we would need moderation tools to unset that flag for abusers.

**Comment by hemebond** [comment]
I've created separate issues for everything except Reviews. Do you want discussions on each map package listing?

**Comment by SpiritQuaddicted** [comment]
Nice, thanks!

Yeah, each package should have discussions.

**Comment by hemebond** [comment]
Signed up for Quaddicted and now see that it works like Moddb. Will create new issues for the review and comment systems.
