### ISSUE TITLE
Check input limits on comments

### ISSUE THREAD

**Issue by hemebond** [hemebond/quaddicted#35]
Especially anonymous comments.

**Comment by SpiritQuaddicted** [comment]
I'd be fine with a really large limitation on length (4096 characters?) just to not allow anything that could be a technical issue.

Content-wise anything text should be fine, emojis, whatever. Of course there needs to be proper handling to avoid any kind of malicious injections. I have strong feelings against embedding anything non-text like images or videos.

I liked having Markdown but am not sure it was a good idea for the issue of links_with_underscores alone, at least currently where people cannot edit their posts. Some sort of markup system (I like Markdown but bbcode is often enough) would be great!

**Comment by hemebond** [comment]
The max length is just the default for django-contrib-comments, 3000.
