### ISSUE TITLE
Map listing ratings

### ISSUE THREAD

**Issue by hemebond** [hemebond/quaddicted#8]
Allow users to rate maps on a scale of 1 to 5 by clicking on some sort of range input (currently a row of 5 hearts).

Each rating will make the map listing update its rating as an average of all ratings.

**Comment by SpiritQuaddicted** [comment]
The "average" user rating is calculated using a weighted bayesian formula after https://www.evanmiller.org/how-not-to-sort-by-average-rating.html , this was necessary to prevent some brigading and to have a meaningful order: https://github.com/SpiritQuaddicted/Quaddicted-reviews/blob/master/index.php#L187

I also scaled the results to the 1-5 range, forgot to commit that though. That part is in PHP for some reason anyways so not too useful.

**Comment by hemebond** [comment]
It is now possible to add and update a rating on the details page for a package. User ratings are also listed on each user comment.
